[workspace]
members = ["aviutl", "apng", "gif"]
default-members = ["apng", "gif"]
resolver = "3"

[workspace.dependencies]
windows = { version = "0.61" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
