[package]
name = "webp_output"
version.workspace = true
edition = "2024"

[lib]
name = "webp_output"
crate-type = ["cdylib"]

[dependencies]
aviutl2 = { path = "../../libs/aviutl2" }
webp_encoder = { path = "../../libs/webp-encoder" }
win32-ui = { workspace = true }
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }

[dev-dependencies]
aviutl2_host = { path = "../../libs/aviutl2-host" }
image-webp = "0.2"
