[package]
name = "webp_output"
version = "1.1.2"
edition = "2024"

[lib]
name = "webp_output"
crate-type = ["cdylib"]

[dependencies]
aviutl2 = { path = "../../libs/aviutl2" }
webp_encoder = { path = "../../libs/webp-encoder" }
win32_dialog = { path = "../../libs/dialog" }
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }
