[package]
name = "avif_output"
version.workspace = true
edition = "2024"

[lib]
name = "avif_output"
crate-type = ["cdylib"]

[dependencies]
aviutl2 = { path = "../../libs/aviutl2" }
avif_encoder = { path = "../../libs/avif-encoder" }
win32-ui = { workspace = true }
windows = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_UI_WindowsAndMessaging",
] }
