[package]
name = "png_output"
version.workspace = true
edition = "2024"

[lib]
name = "png_output"
crate-type = ["cdylib"]

[dependencies]
apng_encoder = { path = "../../libs/apng-encoder" }
aviutl2 = { path = "../../libs/aviutl2" }
win32-ui = { workspace = true }
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }

[dev-dependencies]
aviutl2_host = { path = "../../libs/aviutl2-host" }
png = "0.18"
