[package]
name = "png_output"
version = "1.1.2"
edition = "2024"

[lib]
name = "png_output"
crate-type = ["cdylib"]

[dependencies]
apng_encoder = { path = "../../libs/apng-encoder" }
aviutl2 = { path = "../../libs/aviutl2" }
win32_dialog = { path = "../../libs/dialog" }
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }
