[package]
name = "gif_output"
version.workspace = true
edition = "2024"

[lib]
name = "gif_output"
crate-type = ["cdylib"]

[dependencies]
aviutl2 = { path = "../../libs/aviutl2" }
gif_encoder = { path = "../../libs/gif-encoder" }
win32-ui = { workspace = true }
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }

[dev-dependencies]
aviutl2_host = { path = "../../libs/aviutl2-host" }
gif = "0.13"
