[release]
package_id = "aviutl2-animated-image-output-webp"
package_name = "AviUtl2 アニメーション画像出力 (WebP)"
package_information = "AviUtl2 アニメーション画像出力 WebP v{version}"
zip_name = "{id}-webp-v{version}"
include = ["webp_output", "third_party_licences"]

[artifacts.third_party_licences]
destination = "THIRD-PARTY-LICENCES.txt"
source = "target/third-party/THIRD-PARTY-LICENCES.txt"
