name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      rust-changed: ${{ steps.changes.outputs.rust_any_changed }}
      frontend-changed: ${{ steps.changes.outputs.frontend_any_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changes
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
        with:
          files_yaml: |
            rust:
              - '**/*.rs'
              - '**/Cargo.toml'
              - '**/Cargo.lock'
            frontend:
              - '**/*.{ts,tsx,js,jsx,json,html,css,md}'
              - 'package.json'
              - 'bun.lock'
              - 'biome.jsonc'

  rust-checks:
    name: Rust Checks
    runs-on: windows-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.rust-changed == 'true'
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install NASM
        run: |
          choco install nasm -y
          echo "C:\Program Files\NASM" >> $GITHUB_PATH

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check Build
        run: cargo build --target x86_64-pc-windows-msvc --locked

  frontend-checks:
    name: Frontend Checks
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend-changed == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run lint
        run: bun run lint

      - name: Build frontend
        run: bun run build
